export interface SODViolation {
  id: string;
  role1: string;
  role2: string;
  userId: string;
  userName: string;
  department: string;
  riskLevel: 'High' | 'Medium' | 'Low';
  riskScore: number;
  financialExposure: number;
  description: string;
  lastDetected: string;
  status: 'Active' | 'Remediated' | 'Accepted';
}

export interface ITGCControl {
  id: string;
  controlName: string;
  category: 'Change Management' | 'Access Management' | 'Operations' | 'Disaster Recovery';
  status: 'Compliant' | 'Non-Compliant' | 'In Progress' | 'Not Tested';
  frequency: string;
  lastTested: string;
  testResult: string;
  owner: string;
}

export interface RiskProcess {
  id: string;
  processName: string;
  department: string;
  riskScore: number;
  businessValue: string;
  incidents: number;
  controlGaps: number;
  trend: 'up' | 'down' | 'stable';
}

export interface AuditReport {
  id: string;
  reportName: string;
  date: string;
  period: string;
  totalViolations: number;
  highRiskCount: number;
  mediumRiskCount: number;
  complianceScore: number;
  recommendations: string[];
}

export interface IntegrationStatus {
  id: string;
  name: string;
  system: string;
  status: 'Connected' | 'Disconnected' | 'Error';
  lastSync: string;
  recordsProcessed: number;
  errorCount: number;
}

export const sodViolations: SODViolation[] = [
  {
    id: 'SOD001',
    role1: 'Financial Analyst',
    role2: 'AP Processor',
    userId: 'U12345',
    userName: 'James Mitchell',
    department: 'Finance',
    riskLevel: 'High',
    riskScore: 94,
    financialExposure: 2500000,
    description: 'User has ability to both create and approve purchase orders exceeding $10,000',
    lastDetected: '2026-04-02',
    status: 'Active',
  },
  {
    id: 'SOD002',
    role1: 'System Administrator',
    role2: 'Database Administrator',
    userId: 'U12346',
    userName: 'Patricia Alvarez',
    department: 'IT',
    riskLevel: 'High',
    riskScore: 89,
    financialExposure: 1800000,
    description: 'Full system and database access without segregation of duties',
    lastDetected: '2026-04-01',
    status: 'Active',
  },
  {
    id: 'SOD003',
    role1: 'Account Receivable',
    role2: 'Credit Manager',
    userId: 'U12347',
    userName: 'Michael Chen',
    department: 'Finance',
    riskLevel: 'High',
    riskScore: 87,
    financialExposure: 1200000,
    description: 'Can both issue credit memos and reconcile customer accounts',
    lastDetected: '2026-03-28',
    status: 'Active',
  },
  {
    id: 'SOD004',
    role1: 'Payroll Manager',
    role2: 'HR Specialist',
    userId: 'U12348',
    userName: 'Sarah Johnson',
    department: 'HR',
    riskLevel: 'High',
    riskScore: 85,
    financialExposure: 950000,
    description: 'User can process payroll and approve wage changes without authorization',
    lastDetected: '2026-03-25',
    status: 'Active',
  },
  {
    id: 'SOD005',
    role1: 'Inventory Manager',
    role2: 'Warehouse Supervisor',
    userId: 'U12349',
    userName: 'David Rodriguez',
    department: 'Operations',
    riskLevel: 'Medium',
    riskScore: 72,
    financialExposure: 650000,
    description: 'Can both adjust inventory records and perform physical counts',
    lastDetected: '2026-03-30',
    status: 'Active',
  },
  {
    id: 'SOD006',
    role1: 'General Ledger Accountant',
    role2: 'Accounts Payable',
    userId: 'U12350',
    userName: 'Emma Thompson',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 68,
    financialExposure: 580000,
    description: 'Can record and reconcile transactions without independent review',
    lastDetected: '2026-03-22',
    status: 'Active',
  },
  {
    id: 'SOD007',
    role1: 'Fixed Asset Manager',
    role2: 'Budget Controller',
    userId: 'U12351',
    userName: 'Robert Kim',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 65,
    financialExposure: 520000,
    description: 'Can add assets and approve depreciation schedules',
    lastDetected: '2026-03-20',
    status: 'Remediated',
  },
  {
    id: 'SOD008',
    role1: 'Accounts Receivable Supervisor',
    role2: 'Collections Officer',
    userId: 'U12352',
    userName: 'Lisa Anderson',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 62,
    financialExposure: 480000,
    description: 'Can record and write-off uncollectible accounts',
    lastDetected: '2026-03-18',
    status: 'Active',
  },
  {
    id: 'SOD009',
    role1: 'Change Manager',
    role2: 'System Administrator',
    userId: 'U12353',
    userName: 'James Martinez',
    department: 'IT',
    riskLevel: 'High',
    riskScore: 83,
    financialExposure: 1100000,
    description: 'Can request and implement system changes without approval',
    lastDetected: '2026-04-03',
    status: 'Active',
  },
  {
    id: 'SOD010',
    role1: 'Access Control Officer',
    role2: 'Security Manager',
    userId: 'U12354',
    userName: 'Susan Davis',
    department: 'IT',
    riskLevel: 'High',
    riskScore: 81,
    financialExposure: 950000,
    description: 'Can grant and revoke access without segregated review',
    lastDetected: '2026-03-31',
    status: 'Active',
  },
  {
    id: 'SOD011',
    role1: 'Procurement Officer',
    role2: 'Purchase Requester',
    userId: 'U12355',
    userName: 'Thomas Wilson',
    department: 'Procurement',
    riskLevel: 'Medium',
    riskScore: 70,
    financialExposure: 600000,
    description: 'Can create and process purchases below threshold',
    lastDetected: '2026-03-29',
    status: 'Active',
  },
  {
    id: 'SOD012',
    role1: 'Vendor Master Maintainer',
    role2: 'Payment Processor',
    userId: 'U12356',
    userName: 'Angela Brown',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 67,
    financialExposure: 550000,
    description: 'Can add vendors and process payments to those vendors',
    lastDetected: '2026-03-27',
    status: 'Active',
  },
  {
    id: 'SOD013',
    role1: 'Revenue Manager',
    role2: 'Invoice Approver',
    userId: 'U12357',
    userName: 'Kevin Zhang',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 64,
    financialExposure: 490000,
    description: 'Can record and approve revenue transactions',
    lastDetected: '2026-03-24',
    status: 'Accepted',
  },
  {
    id: 'SOD014',
    role1: 'Compliance Officer',
    role2: 'Internal Auditor',
    userId: 'U12358',
    userName: 'Diana Martinez',
    department: 'Audit',
    riskLevel: 'Low',
    riskScore: 45,
    financialExposure: 200000,
    description: 'Can review and approve compliance reports',
    lastDetected: '2026-03-23',
    status: 'Active',
  },
  {
    id: 'SOD015',
    role1: 'Tax Manager',
    role2: 'Tax Processor',
    userId: 'U12359',
    userName: 'Paul Johnson',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 66,
    financialExposure: 530000,
    description: 'Can calculate and file tax returns without review',
    lastDetected: '2026-03-26',
    status: 'Active',
  },
  {
    id: 'SOD016',
    role1: 'Treasury Officer',
    role2: 'Cash Manager',
    userId: 'U12360',
    userName: 'Rebecca White',
    department: 'Finance',
    riskLevel: 'High',
    riskScore: 86,
    financialExposure: 3200000,
    description: 'Can initiate and approve wire transfers',
    lastDetected: '2026-04-04',
    status: 'Active',
  },
  {
    id: 'SOD017',
    role1: 'Loan Officer',
    role2: 'Credit Approver',
    userId: 'U12361',
    userName: 'Mark Thompson',
    department: 'Credit',
    riskLevel: 'Medium',
    riskScore: 69,
    financialExposure: 620000,
    description: 'Can request and approve credit limit increases',
    lastDetected: '2026-03-21',
    status: 'Active',
  },
  {
    id: 'SOD018',
    role1: 'Insurance Claims Adjuster',
    role2: 'Claims Authorizer',
    userId: 'U12362',
    userName: 'Catherine Lee',
    department: 'Insurance',
    riskLevel: 'Medium',
    riskScore: 63,
    financialExposure: 450000,
    description: 'Can investigate and approve insurance claims',
    lastDetected: '2026-03-19',
    status: 'Active',
  },
  {
    id: 'SOD019',
    role1: 'Benefits Administrator',
    role2: 'Payroll Processor',
    userId: 'U12363',
    userName: 'Jennifer Davis',
    department: 'HR',
    riskLevel: 'Low',
    riskScore: 52,
    financialExposure: 280000,
    description: 'Can enroll employees and process benefit deductions',
    lastDetected: '2026-03-17',
    status: 'Active',
  },
  {
    id: 'SOD020',
    role1: 'Accounts Payable Manager',
    role2: 'Invoice Reviewer',
    userId: 'U12364',
    userName: 'William Garcia',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 61,
    financialExposure: 410000,
    description: 'Can create invoices and approve payments',
    lastDetected: '2026-03-16',
    status: 'Active',
  },
  {
    id: 'SOD021',
    role1: 'Budget Director',
    role2: 'Expense Reviewer',
    userId: 'U12365',
    userName: 'Nicole Taylor',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 60,
    financialExposure: 400000,
    description: 'Can set budgets and approve exceptions',
    lastDetected: '2026-03-15',
    status: 'Active',
  },
  {
    id: 'SOD022',
    role1: 'Revenue Accountant',
    role2: 'Sales Approver',
    userId: 'U12366',
    userName: 'Christopher Brown',
    department: 'Finance',
    riskLevel: 'Low',
    riskScore: 48,
    financialExposure: 220000,
    description: 'Can record sales and reconcile accounts',
    lastDetected: '2026-03-14',
    status: 'Active',
  },
  {
    id: 'SOD023',
    role1: 'Expense Manager',
    role2: 'Finance Analyst',
    userId: 'U12367',
    userName: 'Laura Wilson',
    department: 'Finance',
    riskLevel: 'Low',
    riskScore: 50,
    financialExposure: 260000,
    description: 'Can submit and approve expense reports',
    lastDetected: '2026-03-13',
    status: 'Active',
  },
  {
    id: 'SOD024',
    role1: 'General Ledger Controller',
    role2: 'Financial Analyst',
    userId: 'U12368',
    userName: 'Steven Martinez',
    department: 'Finance',
    riskLevel: 'Medium',
    riskScore: 59,
    financialExposure: 380000,
    description: 'Can post and reconcile general ledger',
    lastDetected: '2026-03-12',
    status: 'Active',
  },
  {
    id: 'SOD025',
    role1: 'Audit Trail Manager',
    role2: 'System Administrator',
    userId: 'U12369',
    userName: 'Amanda Martinez',
    department: 'IT',
    riskLevel: 'High',
    riskScore: 82,
    financialExposure: 1050000,
    description: 'Can modify audit logs without restriction',
    lastDetected: '2026-03-30',
    status: 'Active',
  },
];

export const itgcControls: ITGCControl[] = [
  {
    id: 'ITGC001',
    controlName: 'Change Request Authorization',
    category: 'Change Management',
    status: 'Compliant',
    frequency: 'Per Change',
    lastTested: '2026-04-01',
    testResult: 'Pass',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC002',
    controlName: 'Change Testing Requirements',
    category: 'Change Management',
    status: 'Compliant',
    frequency: 'Per Change',
    lastTested: '2026-04-01',
    testResult: 'Pass',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC003',
    controlName: 'Change Implementation Review',
    category: 'Change Management',
    status: 'In Progress',
    frequency: 'Per Change',
    lastTested: '2026-03-28',
    testResult: 'In Testing',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC004',
    controlName: 'Rollback Procedures',
    category: 'Change Management',
    status: 'Non-Compliant',
    frequency: 'Per Change',
    lastTested: '2026-03-25',
    testResult: 'Fail - Missing documentation',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC005',
    controlName: 'User Access Provisioning',
    category: 'Access Management',
    status: 'Compliant',
    frequency: 'Monthly',
    lastTested: '2026-03-31',
    testResult: 'Pass',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC006',
    controlName: 'User Access Deprovisioning',
    category: 'Access Management',
    status: 'Compliant',
    frequency: 'Monthly',
    lastTested: '2026-03-31',
    testResult: 'Pass',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC007',
    controlName: 'Privileged Access Management',
    category: 'Access Management',
    status: 'In Progress',
    frequency: 'Quarterly',
    lastTested: '2026-03-20',
    testResult: 'In Testing',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC008',
    controlName: 'Access Reviews',
    category: 'Access Management',
    status: 'Compliant',
    frequency: 'Quarterly',
    lastTested: '2026-03-15',
    testResult: 'Pass',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC009',
    controlName: 'Segregation of Duties Reviews',
    category: 'Access Management',
    status: 'In Progress',
    frequency: 'Quarterly',
    lastTested: '2026-03-10',
    testResult: 'In Testing',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC010',
    controlName: 'Password Policy Enforcement',
    category: 'Access Management',
    status: 'Compliant',
    frequency: 'Continuous',
    lastTested: '2026-04-03',
    testResult: 'Pass',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC011',
    controlName: 'Backup Completeness',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Daily',
    lastTested: '2026-04-04',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC012',
    controlName: 'Backup Restoration Testing',
    category: 'Operations',
    status: 'Non-Compliant',
    frequency: 'Quarterly',
    lastTested: '2026-02-15',
    testResult: 'Fail - Test not performed',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC013',
    controlName: 'Database Integrity Checks',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Daily',
    lastTested: '2026-04-04',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC014',
    controlName: 'System Availability Monitoring',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Continuous',
    lastTested: '2026-04-04',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC015',
    controlName: 'Performance Monitoring',
    category: 'Operations',
    status: 'In Progress',
    frequency: 'Daily',
    lastTested: '2026-03-28',
    testResult: 'In Testing',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC016',
    controlName: 'Incident Response Procedures',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Per Incident',
    lastTested: '2026-03-20',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC017',
    controlName: 'Audit Logging',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Continuous',
    lastTested: '2026-04-02',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC018',
    controlName: 'Log Review and Monitoring',
    category: 'Operations',
    status: 'Non-Compliant',
    frequency: 'Daily',
    lastTested: '2026-03-15',
    testResult: 'Fail - Incomplete',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC019',
    controlName: 'Disaster Recovery Plan',
    category: 'Disaster Recovery',
    status: 'Compliant',
    frequency: 'Annually',
    lastTested: '2026-02-10',
    testResult: 'Pass',
    owner: 'Michael Chang',
  },
  {
    id: 'ITGC020',
    controlName: 'Disaster Recovery Testing',
    category: 'Disaster Recovery',
    status: 'In Progress',
    frequency: 'Quarterly',
    lastTested: '2026-02-28',
    testResult: 'In Testing',
    owner: 'Michael Chang',
  },
  {
    id: 'ITGC021',
    controlName: 'Alternate Processing Facilities',
    category: 'Disaster Recovery',
    status: 'Compliant',
    frequency: 'Quarterly',
    lastTested: '2026-03-01',
    testResult: 'Pass',
    owner: 'Michael Chang',
  },
  {
    id: 'ITGC022',
    controlName: 'Data Recovery Time Objectives',
    category: 'Disaster Recovery',
    status: 'Compliant',
    frequency: 'Quarterly',
    lastTested: '2026-03-05',
    testResult: 'Pass',
    owner: 'Michael Chang',
  },
  {
    id: 'ITGC023',
    controlName: 'Business Continuity Plan',
    category: 'Disaster Recovery',
    status: 'Non-Compliant',
    frequency: 'Annually',
    lastTested: '2026-01-15',
    testResult: 'Fail - Outdated',
    owner: 'Michael Chang',
  },
  {
    id: 'ITGC024',
    controlName: 'Off-site Backup Storage',
    category: 'Disaster Recovery',
    status: 'Compliant',
    frequency: 'Monthly',
    lastTested: '2026-03-30',
    testResult: 'Pass',
    owner: 'Michael Chang',
  },
  {
    id: 'ITGC025',
    controlName: 'Backup Encryption',
    category: 'Disaster Recovery',
    status: 'Compliant',
    frequency: 'Per Change',
    lastTested: '2026-03-28',
    testResult: 'Pass',
    owner: 'Michael Chang',
  },
  {
    id: 'ITGC026',
    controlName: 'Configuration Management',
    category: 'Change Management',
    status: 'In Progress',
    frequency: 'Quarterly',
    lastTested: '2026-03-22',
    testResult: 'In Testing',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC027',
    controlName: 'System Access Termination',
    category: 'Access Management',
    status: 'Compliant',
    frequency: 'Per Termination',
    lastTested: '2026-04-01',
    testResult: 'Pass',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC028',
    controlName: 'Change Emergency Procedures',
    category: 'Change Management',
    status: 'Non-Compliant',
    frequency: 'Quarterly',
    lastTested: '2026-02-28',
    testResult: 'Fail - Not documented',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC029',
    controlName: 'Data Classification',
    category: 'Access Management',
    status: 'In Progress',
    frequency: 'Quarterly',
    lastTested: '2026-03-25',
    testResult: 'In Testing',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC030',
    controlName: 'System Documentation',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Per Change',
    lastTested: '2026-03-29',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC031',
    controlName: 'Vendor Management Controls',
    category: 'Operations',
    status: 'Non-Compliant',
    frequency: 'Annually',
    lastTested: '2026-01-30',
    testResult: 'Fail - Incomplete assessment',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC032',
    controlName: 'Network Access Controls',
    category: 'Access Management',
    status: 'Compliant',
    frequency: 'Quarterly',
    lastTested: '2026-03-31',
    testResult: 'Pass',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC033',
    controlName: 'Physical Access Controls',
    category: 'Access Management',
    status: 'Compliant',
    frequency: 'Monthly',
    lastTested: '2026-03-31',
    testResult: 'Pass',
    owner: 'Susan Davis',
  },
  {
    id: 'ITGC034',
    controlName: 'System Patch Management',
    category: 'Operations',
    status: 'In Progress',
    frequency: 'Monthly',
    lastTested: '2026-03-28',
    testResult: 'In Testing',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC035',
    controlName: 'Antivirus Management',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Continuous',
    lastTested: '2026-04-03',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC036',
    controlName: 'Change Control Documentation',
    category: 'Change Management',
    status: 'Compliant',
    frequency: 'Per Change',
    lastTested: '2026-04-01',
    testResult: 'Pass',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC037',
    controlName: 'Application Change Approval',
    category: 'Change Management',
    status: 'Compliant',
    frequency: 'Per Change',
    lastTested: '2026-04-01',
    testResult: 'Pass',
    owner: 'James Morrison',
  },
  {
    id: 'ITGC038',
    controlName: 'Incident Logging and Tracking',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Per Incident',
    lastTested: '2026-04-02',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC039',
    controlName: 'Problem Management Process',
    category: 'Operations',
    status: 'In Progress',
    frequency: 'Quarterly',
    lastTested: '2026-03-20',
    testResult: 'In Testing',
    owner: 'Robert Williams',
  },
  {
    id: 'ITGC040',
    controlName: 'Service Level Agreements',
    category: 'Operations',
    status: 'Compliant',
    frequency: 'Quarterly',
    lastTested: '2026-03-31',
    testResult: 'Pass',
    owner: 'Robert Williams',
  },
];

export const riskProcesses: RiskProcess[] = [
  {
    id: 'RISK001',
    processName: 'Order to Cash',
    department: 'Sales & Finance',
    riskScore: 82,
    businessValue: '$850M',
    incidents: 3,
    controlGaps: 2,
    trend: 'up',
  },
  {
    id: 'RISK002',
    processName: 'Procure to Pay',
    department: 'Procurement & Finance',
    riskScore: 78,
    businessValue: '$620M',
    incidents: 2,
    controlGaps: 3,
    trend: 'stable',
  },
  {
    id: 'RISK003',
    processName: 'Record to Report',
    department: 'Finance & IT',
    riskScore: 71,
    businessValue: '$1.2B',
    incidents: 1,
    controlGaps: 1,
    trend: 'down',
  },
  {
    id: 'RISK004',
    processName: 'Plan to Produce',
    department: 'Operations',
    riskScore: 65,
    businessValue: '$450M',
    incidents: 0,
    controlGaps: 2,
    trend: 'down',
  },
  {
    id: 'RISK005',
    processName: 'Hire to Retire',
    department: 'HR & Payroll',
    riskScore: 58,
    businessValue: '$280M',
    incidents: 1,
    controlGaps: 1,
    trend: 'stable',
  },
  {
    id: 'RISK006',
    processName: 'Financial Planning',
    department: 'Finance',
    riskScore: 72,
    businessValue: '$500M',
    incidents: 2,
    controlGaps: 2,
    trend: 'up',
  },
  {
    id: 'RISK007',
    processName: 'Asset Management',
    department: 'Operations & Finance',
    riskScore: 62,
    businessValue: '$380M',
    incidents: 0,
    controlGaps: 1,
    trend: 'down',
  },
  {
    id: 'RISK008',
    processName: 'IT Operations',
    department: 'IT',
    riskScore: 68,
    businessValue: '$120M',
    incidents: 2,
    controlGaps: 3,
    trend: 'stable',
  },
  {
    id: 'RISK009',
    processName: 'Revenue Recognition',
    department: 'Finance & Sales',
    riskScore: 76,
    businessValue: '$750M',
    incidents: 1,
    controlGaps: 2,
    trend: 'up',
  },
  {
    id: 'RISK010',
    processName: 'Inventory Management',
    department: 'Operations',
    riskScore: 55,
    businessValue: '$320M',
    incidents: 0,
    controlGaps: 1,
    trend: 'down',
  },
  {
    id: 'RISK011',
    processName: 'Treasury Management',
    department: 'Finance',
    riskScore: 79,
    businessValue: '$2.1B',
    incidents: 2,
    controlGaps: 2,
    trend: 'stable',
  },
  {
    id: 'RISK012',
    processName: 'Credit Management',
    department: 'Finance & Sales',
    riskScore: 64,
    businessValue: '$410M',
    incidents: 1,
    controlGaps: 1,
    trend: 'down',
  },
  {
    id: 'RISK013',
    processName: 'Tax Compliance',
    department: 'Finance',
    riskScore: 61,
    businessValue: '$180M',
    incidents: 0,
    controlGaps: 2,
    trend: 'stable',
  },
  {
    id: 'RISK014',
    processName: 'Data Security',
    department: 'IT',
    riskScore: 85,
    businessValue: '$600M',
    incidents: 1,
    controlGaps: 4,
    trend: 'up',
  },
  {
    id: 'RISK015',
    processName: 'Compliance Management',
    department: 'Legal & Audit',
    riskScore: 53,
    businessValue: '$100M',
    incidents: 0,
    controlGaps: 0,
    trend: 'down',
  },
];

export const auditReports: AuditReport[] = [
  {
    id: 'RPT001',
    reportName: 'Q1 2026 SOD Audit Report',
    date: '2026-03-31',
    period: 'Q1 2026',
    totalViolations: 25,
    highRiskCount: 11,
    mediumRiskCount: 10,
    complianceScore: 62,
    recommendations: [
      'Implement automated SOD monitoring in ERP system',
      'Strengthen vendor master access controls',
      'Review and remediate Treasury management segregation',
      'Implement role-based access control framework',
      'Establish quarterly SOD certification process',
    ],
  },
  {
    id: 'RPT002',
    reportName: 'ITGC Control Testing Report',
    date: '2026-03-15',
    period: 'Q1 2026',
    totalViolations: 4,
    highRiskCount: 0,
    mediumRiskCount: 4,
    complianceScore: 84,
    recommendations: [
      'Complete rollback procedure documentation',
      'Schedule quarterly disaster recovery testing',
      'Update business continuity plan',
      'Implement automated log review procedures',
      'Complete privileged access management review',
    ],
  },
  {
    id: 'RPT003',
    reportName: 'Financial Close Process Audit',
    date: '2026-02-28',
    period: 'Q4 2025',
    totalViolations: 8,
    highRiskCount: 2,
    mediumRiskCount: 4,
    complianceScore: 76,
    recommendations: [
      'Strengthen manual journal entry controls',
      'Implement enhanced approval workflows',
      'Add reconciliation verification procedures',
      'Increase monitoring of period-end processes',
      'Document manual control procedures',
    ],
  },
  {
    id: 'RPT004',
    reportName: 'Procurement Controls Assessment',
    date: '2026-02-15',
    period: 'Q4 2025',
    totalViolations: 6,
    highRiskCount: 1,
    mediumRiskCount: 3,
    complianceScore: 79,
    recommendations: [
      'Implement three-way matching for all purchases',
      'Enhance purchase order authorization limits',
      'Strengthen vendor evaluation process',
      'Add exception reporting for unusual purchases',
      'Implement automated invoice validation',
    ],
  },
  {
    id: 'RPT005',
    reportName: 'Annual Compliance Review',
    date: '2026-01-31',
    period: 'FY 2025',
    totalViolations: 42,
    highRiskCount: 15,
    mediumRiskCount: 18,
    complianceScore: 68,
    recommendations: [
      'Establish integrated audit dashboard',
      'Implement real-time SOD monitoring',
      'Strengthen IT access control reviews',
      'Enhance continuous auditing capabilities',
      'Increase testing frequency for high-risk areas',
    ],
  },
];

export const integrationStatuses: IntegrationStatus[] = [
  {
    id: 'INT001',
    name: 'NetSuite',
    system: 'ERP',
    status: 'Connected',
    lastSync: '2026-04-04 14:32:00',
    recordsProcessed: 142560,
    errorCount: 0,
  },
  {
    id: 'INT002',
    name: 'SAP',
    system: 'ERP',
    status: 'Connected',
    lastSync: '2026-04-04 13:15:00',
    recordsProcessed: 98340,
    errorCount: 2,
  },
  {
    id: 'INT003',
    name: 'Oracle',
    system: 'ERP',
    status: 'Disconnected',
    lastSync: '2026-04-02 09:45:00',
    recordsProcessed: 0,
    errorCount: 5,
  },
  {
    id: 'INT004',
    name: 'Workday',
    system: 'HCM',
    status: 'Connected',
    lastSync: '2026-04-04 15:20:00',
    recordsProcessed: 45230,
    errorCount: 1,
  },
  {
    id: 'INT005',
    name: 'Salesforce',
    system: 'CRM',
    status: 'Error',
    lastSync: '2026-04-03 18:30:00',
    recordsProcessed: 0,
    errorCount: 12,
  },
  {
    id: 'INT006',
    name: 'ServiceNow',
    system: 'ITSM',
    status: 'Connected',
    lastSync: '2026-04-04 14:50:00',
    recordsProcessed: 23450,
    errorCount: 0,
  },
];
